### ISSUE TITLE
insertfix-mixin migration to XTerm 5

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/XTermConsoleAddon#70]
InsertFix does not work with XTerm 5.1.0. Reported the original issue upstream https://github.com/xtermjs/xterm.js/issues/4359 in case it can be fixed there, so that we can get rid of the ~fix~ hack altogether.

https://github.com/FlowingCode/XTermConsoleAddon/blob/772d5625dca5502a5fb806bebe04117101552913/src/main/resources/META-INF/frontend/fc-xterm/xterm-insertfix-mixin.ts#L72
```
Uncaught TypeError: Cannot read properties of undefined (reading 'markDirty')
    at InsertFixAddon.printHandler (xterm-insertfix-mixin.ts:72:36)
    at c.newPrintHandler [as _printHandler] (xterm-insertfix-mixin.ts:31:83)
    at c.parse (EscapeSequenceParser.ts:632:20)
    at E.parse (InputHandler.ts:485:35)
    at n._action (CoreTerminal.ts:145:99)
    at n._innerWrite (WriteBuffer.ts:164:27)
    at n.write (WriteBuffer.ts:120:14)
    at I.write (CoreTerminal.ts:155:23)
    at e2.Terminal.write (Terminal.ts:217:16)
    at xterm-element.ts:164:14
    at t2.EventEmitter.fire (EventEmitter.ts:55:16)
    at EventEmitter.ts:68:23
    at t2.EventEmitter.fire (EventEmitter.ts:55:16)
    at d.triggerDataEvent (CoreService.ts:77:18)
    at I._keyDown (Terminal.ts:1065:22)
    at HTMLTextAreaElement.<anonymous> (Terminal.ts:392:99)
```

**Comment by javier-godoy** [comment]
From https://github.com/xtermjs/xterm.js/discussions/4360#discussioncomment-4505991
>xtermjs implements IRM and DECAWM following these DEC VT semantics:
>> If the DECAWM function is set, then graphic characters received when the cursor is at the right border of the page appear at the beginning of the next line. Any text on the page scrolls up if the cursor is at the end of the scrolling region.
If IRM mode is set, then new characters move characters in page memory to the right. Characters moved past the page's right border are lost.
>
> **Thus wrap-around does not apply in insert mode to moved chars**

Since `xterm.js` works as intended, let's just migrate the insertfix-mixin. 
Note that `_dirtyRowService` has been renamed to `_dirtyRowTracker`
