### ISSUE TITLE
properties of undefined .isWrapped error

### ISSUE THREAD

**Issue by ElTankesitoArceus** [FlowingCode/XTermConsoleAddon#80]
Im trying to use XTerm as a console for a minecraft server, and every time I get this error after 20 lines or so
![image](https://github.com/FlowingCode/XTermConsoleAddon/assets/98356553/6f39e255-17fb-4b80-940d-c2dad78d7b41)

`Uncaught TypeError: Cannot set properties of undefined (setting 'isWrapped') (http://localhost:8080/VAADIN/build/generated-flow-imports-4b12332d.js:16123:3143)`

Mi XTerm variable looks like this

>         terminal = new XTerm(); 
>         terminal.setCursorBlink(true);
>         terminal.setCursorStyle(CursorStyle.UNDERLINE);
>         terminal.setCopySelection(true);
>         terminal.setUseSystemClipboard(UseSystemClipboard.READWRITE);
>         terminal.setPasteWithRightClick(true);
>         terminal.setFitOnResize(true);
>         terminal.setRendererType(RendererType.CANVAS);
>         terminal.setHeightFull();
>         terminal.setWidthFull();
>         terminal.setSizeFull();
>         TerminalHistory.extend(terminal);

And for writing lines I use

>          for (String line = serverInput.readLine(); line != null; line = serverInput.readLine()) {
>                // System.out.println(line);
>                 terminal.writeln(line);
>                 terminal.scrollToBottom();
>                 ui.push();
>           }

In this case im trying to run a [velocity server](https://papermc.io/downloads/velocity) with a ProcessBuilder in a separate thread (the serverInput variable im using is the Buffered Reader of the process)

The line it strarts givin the error at is 
`        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]`
With is part of an `Address already in use: bind` error caused by the port allready being used, witch im specting when running the JAR.

**Comment by ElTankesitoArceus** [comment]
@javier-godoy yes, I did

**Comment by javier-godoy** [comment]
Which version of Vaadin and which version of the add-on are you using?

**Comment by javier-godoy** [comment]
We had just released 2.2.0, which may have a different behavior (it upgrades the version of xterm.js) although it has no direct fix for this issue. 

Based on the error message, I think the issue likely related to the following line (which is a workaround for #70)
https://github.com/FlowingCode/XTermConsoleAddon/blob/97fd2fcd7ed45a632a07e7eb92811174d66f6f85/src/main/resources/META-INF/frontend/fc-xterm/xterm-insertfix-mixin.ts#L66

If the error persists with 2.2.0, please let me know if you have some reproducible example of that issue (perhaps it's related to writing a lot of lines at once, or writing long lines) or if you are willing to try some snapshot version with enhanced logs. That fragment of code is rather fragile, and there may be some corner case that is not covered by the integration tests.

**Comment by ElTankesitoArceus** [comment]
I upgraded to 2.2.0 and the error still persists.

Also, i was accesing the web using chrome, but trying **firefox** I get a different error:
![image](https://github.com/FlowingCode/XTermConsoleAddon/assets/98356553/cb1807eb-5e99-4be9-8541-f9ef3f68e4e8)
`TypeError: te is undefined (http://localhost:8080/VAADIN/build/generated-flow-imports-ce79c564.js:16125:3133)`

If you want to reproduce the error, this is the spected output:

```
WARN StatusConsoleListener Advanced terminal features are not available in this environment

ERROR StatusConsoleListener Unable to delete file C:\Users\aramosm\Documents\server\logs\latest.log: java.nio.file.FileSystemException C:\Users\aramosm\Documents\server\logs\latest.log: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso

[09:12:20 INFO]: Booting up Velocity 3.2.0-SNAPSHOT (git-7f776abf-b252)...

[09:12:20 INFO]: Loading localizations...

[09:12:21 INFO]: Connections will use NIO channels, Java compression, Java ciphers

[09:12:21 WARN]: Player info forwarding is disabled! All players will appear to be connecting from the proxy and will have offline-mode UUIDs.

[09:12:21 INFO]: Loading plugins...

[09:12:21 INFO]: Loaded 0 plugins

[09:12:21 INFO]: Done (1,54s)!

[09:12:21 ERROR]: Can't bind to /0.0.0.0:25577
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
        at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
        at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?]
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]   
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT 
(git-7f776abf-b252)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]      
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[paper-1.19.4.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at java.lang.Thread.run(Thread.java:833) [?:?]

```

And it is able to write this before it starts giving the error every time you attempt to write another line:
```
WARN StatusConsoleListener Advanced terminal features are not available in this environment

ERROR StatusConsoleListener Unable to delete file C:\Users\aramosm\Documents\server\logs\latest.log: java.nio.file.FileSystemException C:\Users\aramosm\Documents\server\logs\latest.log: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso

[09:12:20 INFO]: Booting up Velocity 3.2.0-SNAPSHOT (git-7f776abf-b252)...

[09:12:20 INFO]: Loading localizations...

[09:12:21 INFO]: Connections will use NIO channels, Java compression, Java ciphers

[09:12:21 WARN]: Player info forwarding is disabled! All players will appear to be connecting from the proxy and will have offline-mode UUIDs.

[09:12:21 INFO]: Loading plugins...

[09:12:21 INFO]: Loaded 0 plugins

[09:12:21 INFO]: Done (1,54s)!

[09:12:21 ERROR]: Can't bind to /0.0.0.0:25577
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
        at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
        at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?]
```
You can also run the [Velocity server jar](https://papermc.io/downloads/velocity), a minecraft server proxy, on a separate thread and redirect the output to the console. 

Im writing using this in a separate thread:
```java
 int num = inputStream.available();
 if (num > 0) {
    int n = inputStream.read(buffer, 0, Math.min(num, buffer.length));
    String line = new String(buffer, 0, n);
    System.out.println(line);
    final String out = line;
    ui.access(() -> {
        terminal.writeln(out);
        terminal.scrollToBottom();
        ui.push();
    });
}
```
Also, I first tried getting the output from the process with a BufferedReader and .readLine(), but it enters on an infinite loop, probably because the process waits for input.
